_target_: models.models.multi_level_vqvae.encoder.EncoderConv2D
channel_list: [2, 32, 64, 128, 256, 512, 1024, 2048]
dim_change_list: [2, 2, 2, 2, 2, 2, 2] # 2^15 / 2^4 / 2^5
kernel_size: 3
num_res_block_conv: 4
dilation_factor: 2
n_fft: 512
hop_length: 128
win_length: 512
activation_fn:
  _target_: torch.nn.GELU

