defaults:
  - _self_
  - data: lvl1_vqvae
  - learning: vqgan
  - loss: ml_vqvae_long
  - model: ml_vqvae_stft
  - module: vqgan_music
  - optimizer: adamw_vqgan
  - scheduler: none

# Project data
project_name: InfectedPBM
model_name: lvl1_vqgan
resume: null

# Optimizations
use_torch_compile: False
